name: zweipunktlol
title: "Web, Games, LOL"
author: David Curlott
email: curlott@gmail.com
encoding: utf-8
markdown: kramdown
permalink: pretty

# redcarpet:
  # extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "underline", "highlight", "quote", "superscript"]
pygments: true
exclude: ["README.md", "*.scss", "*.sublime-project", "*.sublime-workspace", "*.rb"]


