name: My New Jekyll Site
title: Curlott the Webpage
author: David Curlott
email: curlott@gmail.com
markdown: redcarpet
pygments: true
exclude: ["README.md", "*.scss", "*.sublime-project", "*.sublime-workspace"]


